letra=input("Digite uma letra: ")

if letra=="a":
    print('Abacate/Arara')
elif letra=="b":
    print('Banana/Beija-Flor')
elif letra=="c":
    print('Cereja/Cavalo-Marinho')
elif letra=="d":
    print('Damasco/Dragão-de-Komodo')
elif letra=="e":
    print('Esporão-de-Galo/Elefante')
elif letra=="f":
    print('Formiga/Framboesa')
elif letra=="g":
    print('Guarana/Gato')
elif letra=="h":
    print('Hipopótamo/Haisteria')
elif letra=="i":
    print('iguana/Imbu')
elif letra=="j":
    print('Jabuti/Jaca')
elif letra=="k":
    print('Kiwi/Kiwi')
elif letra=="l":
    print('Lagarta/Laranja')
elif letra=="m":
    print('Mosquito/Manga')
elif letra=="n":
    print('Naja/Noz')
elif letra=="o":
    print('Onça/Oiti')
elif letra=="p":
    print('Pantera/Pera')
elif letra=="q":
    print('Quati/Quii')
elif letra=="r":
    print('Rá/Romã')
elif letra=="s":
    print('Surucucu/Sapota')
elif letra=="t":
    print('Tomate/Touro')
elif letra=="u":
    print('Urubu/Uva')
elif letra=="v":
    print('Veado/Vergamota')
elif letra=="w":
    print('West Highland White Terrier/Wampi')
elif letra=="x":
    print('Xofrango/Xagui')
elif letra=="y":
    print('Yak/Yuzu')
elif letra=="z":
    print('Zebra/Zimbro')
else:
    print("A letra digitada não existe")